Update gumby.shuffle.js
System: gumby-shuffle
Error: $ is undefined
Cause: jQuery not passed to function
Action: Pass jQuery to function as param $